<a href="https://colab.research.google.com/github/jeevana16/my-first-repo/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
list=[23,34,56,78,89]
print(list+list)

[23, 34, 56, 78, 89, 23, 34, 56, 78, 89]


In [3]:
import numpy as np
marks=np.array([23,34,56,77,87])
print(marks+4)

[27 38 60 81 91]


In [5]:
zeros=np.zeros(3)
print(zeros)

[0. 0. 0.]


In [8]:
numbers=np.arange(0,45,7)
print(numbers)

[ 0  7 14 21 28 35 42]


In [9]:
numbers=np.linspace(8,45,9)
print(numbers)

[ 8.    12.625 17.25  21.875 26.5   31.125 35.75  40.375 45.   ]


In [16]:
marks=np.array([45,98,9,78,65])
print(marks.shape)


(5,)


In [17]:
a=np.array([10,24,56,67,89])
print(a)
print(a.shape)

[10 24 56 67 89]
(5,)


In [18]:
print(a.T)

[10 24 56 67 89]


In [22]:
a=np.array([2,4,5,6,7,9,8,7])
print(a.reshape(2,4))

[[2 4 5 6]
 [7 9 8 7]]


In [23]:
numbers=np.arange(1,13)
print(numbers.reshape(-1,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
 print(numbers.size)

12


In [29]:
numbers=np.array( [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(numbers[0:2,:])


[[1 2 3]
 [4 5 6]]


In [30]:
print(numbers[0:1,1:2])

[[2]]


In [31]:
number1=np.array ([
    [1, 2, 3,4],
    [4, 5, 6,5],
    [7, 8, 9,6]
])
number2=np.array([2,4,5])
print(number1+number2)

[[ 3  6  8]
 [ 6  9 11]
 [ 9 12 14]]


In [33]:
a=np.array([
    [1, 2, 3,4],
    [4, 5, 6,5],
    [7, 8, 9,6]
])
b=np.array([2,4,5,4])
print(a+b)

[[ 3  6  8  8]
 [ 6  9 11  9]
 [ 9 12 14 10]]


In [37]:
print(np.random.randint([1,8]))

[0 2]


In [41]:
print(np.random.randint(1,8,size=4))

[1 7 4 1]


In [42]:
np.random.random(223)

array([5.97762924e-01, 6.32544268e-01, 9.59924873e-01, 3.79458510e-01,
       1.23212293e-01, 1.15981306e-01, 7.66659160e-02, 3.29908585e-01,
       5.83436464e-01, 3.78065687e-01, 7.32709389e-01, 7.47665953e-01,
       1.06564850e-01, 8.20049778e-01, 7.40579956e-01, 5.60086945e-01,
       3.19561099e-01, 8.22702251e-01, 6.98627960e-01, 1.07990874e-01,
       9.26127114e-01, 7.32715092e-01, 9.42051173e-01, 6.25608788e-01,
       6.66313763e-01, 5.30006541e-04, 7.70759098e-01, 4.68695794e-01,
       9.00488992e-01, 7.91787926e-01, 1.09014010e-01, 2.79066325e-01,
       4.45856084e-01, 8.47550733e-01, 1.79516515e-01, 8.87237433e-01,
       7.15379455e-01, 9.86110453e-01, 4.90268597e-01, 3.59923278e-01,
       7.71624645e-01, 5.44513266e-01, 2.69727975e-01, 1.34520805e-01,
       3.59420186e-01, 3.59090811e-01, 9.57573275e-01, 8.51049351e-01,
       6.97037347e-01, 2.61634004e-01, 5.08823288e-01, 6.29841066e-01,
       8.50815340e-01, 2.97440916e-01, 5.61496896e-01, 5.22714388e-02,
      

In [44]:
np.random.uniform(8,20,size=4)

array([ 9.12117399, 15.06103427, 16.12332273, 13.85977958])

In [49]:
list=[23,455,56]
np.random.shuffle(list)
print(list)

[455, 56, 23]


In [51]:
np.random.seed(42)


In [55]:
import pandas as pd
scores=pd.Series([32,45,56,78,43])
print(scores)

0    32
1    45
2    56
3    78
4    43
dtype: int64


In [57]:
scores=pd.Series([3,34,56.67,68,78,65])
index=pd.Series(['a','b','c','d','e','f'])
print(index)
print(scores)

0    a
1    b
2    c
3    d
4    e
5    f
dtype: object
0     3.00
1    34.00
2    56.67
3    68.00
4    78.00
5    65.00
dtype: float64


In [61]:
data={
    "name": [ "alive","bob","cat" ],
    "age": [23,45,67],
    "scores": [34,56,78]
}
df=pd.DataFrame(data)
print(df)


    name  age  scores
0  alive   23      34
1    bob   45      56
2    cat   67      78


In [62]:
print(df.shape)

(3, 3)


In [63]:
print(df.columns)

Index(['name', 'age', 'scores'], dtype='object')


In [64]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)


In [66]:
print(df.dtypes)

name      object
age        int64
scores     int64
dtype: object


In [ ]:
pd.read_csv("/archive.zip")

In [70]:
df=pd.read_csv("/Titanic-Dataset.csv")

In [68]:
pd.info()

AttributeError: module 'pandas' has no attribute 'info'

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [72]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [73]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [74]:
import seaborn as sns
titanic = sns.load_dataset("titanic")
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


In [78]:
titanic.shape

(891, 15)

In [80]:
titanic.describe()

,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [79]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [83]:
titanic["age"]

,age
0,22.0
1,38.0
2,26.0
3,35.0
4,35.0
...,...
886,27.0
887,19.0
888,NaN
889,26.0


In [86]:
titanic_renamed=titanic.rename(columns={"sex":"gender"})
titanic_renamed


,survived,pclass,gender,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


In [91]:
print(titanic.iloc[::2])

IndexingError: Too many indexers

In [99]:
titanic[titanic["survived"]==1]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True


In [106]:
titanic[(titanic["age"]>20) &(titanic["pclass"]==1)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
867,0,1,male,31.0,0,0,50.4958,S,First,man,True,A,Southampton,no,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False


In [102]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [107]:
titanic.shape

(891, 15)

In [108]:
import pandas as pd

df = pd.DataFrame({
    "Region": ["East", "West", "North", "South", "East", "West", "North", "South"],
    "Product": ["Laptop", "Mobile", "Tablet", "Laptop", "Mobile", "Tablet", "Laptop", "Mobile"],
    "Sales": [55000, 30000, 24000, 66000, 45000, 36000, 88000, 27000],
    "Quantity": [5, 10, 8, 6, 15, 12, 8, 9]
})

print(df)

  Region Product  Sales  Quantity
0   East  Laptop  55000         5
1   West  Mobile  30000        10
2  North  Tablet  24000         8
3  South  Laptop  66000         6
4   East  Mobile  45000        15
5   West  Tablet  36000        12
6  North  Laptop  88000         8
7  South  Mobile  27000         9


In [113]:
df.groupby("Region")["Sales"].sum()

,Sales
Region,
East,100000
North,112000
South,93000
West,66000


In [117]:
df.groupby[("Region","Product")]["Sales"].sum()

TypeError: 'method' object is not subscriptable

In [118]:
df.groupby(["Region", "Product"])["Sales"].sum()

Region  Product
East    Laptop     55000
        Mobile     45000
North   Laptop     88000
        Tablet     24000
South   Laptop     66000
        Mobile     27000
West    Mobile     30000
        Tablet     36000
Name: Sales, dtype: int64

In [121]:
titanic=sns.load_dataset("titanic")
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


In [122]:
grouped=titanic.groupby("passenger").count()

KeyError: 'passenger'

In [124]:
df.groupby(["Region","Products"])["Sales"].agg(["sum","mean"])

KeyError: 'Products'

In [125]:
import pandas as pd

df = pd.DataFrame({
    "Region": ["East", "West", "North", "South", "East", "West", "North", "South"],
    "Product": ["Laptop", "Mobile", "Tablet", "Laptop", "Mobile", "Tablet", "Laptop", "Mobile"],
    "Sales": [55000, 30000, 24000, 66000, 45000, 36000, 88000, 27000],
    "Quantity": [5, 10, 8, 6, 15, 12, 8, 9]
})

print(df)

  Region Product  Sales  Quantity
0   East  Laptop  55000         5
1   West  Mobile  30000        10
2  North  Tablet  24000         8
3  South  Laptop  66000         6
4   East  Mobile  45000        15
5   West  Tablet  36000        12
6  North  Laptop  88000         8
7  South  Mobile  27000         9


In [144]:
resulted_colums=df.groupby("Region").agg({"Sales":["sum","mean"],"Quantity":["sum","max"]})
resulted_colums

Sales          Quantity    
           sum     mean      sum max
Region                              
East    100000  50000.0       20  15
North   112000  56000.0       16   8
South    93000  46500.0       15   9
West     66000  33000.0       22  12

In [143]:
columns=["Region","sales_sum","sales_mean","quantity_sum","quantity_max"]
resulted_colums=columns

In [129]:
df.groupby(["Region","Product"])["Sales"].sum()

Region  Product
East    Laptop     55000
        Mobile     45000
North   Laptop     88000
        Tablet     24000
South   Laptop     66000
        Mobile     27000
West    Mobile     30000
        Tablet     36000
Name: Sales, dtype: int64

In [146]:
titanic.groupby("pclass")["survived"].agg(["mean","sum"])

,mean,sum
pclass,,
1,0.629630,136
2,0.472826,87
3,0.242363,119


In [145]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')